[package]
name = "metashrew-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bitcoin = "0.31.2"
itertools = "0.12.1"
rlp = "0.5.2"
wasmtime = "19.0.1"
